#!/usr/bin/env python3
"""Solve discrete LQR for the position-integrator plant and write gains to YAML.

Plant model (per axis, decoupled):
    e[k+1] = e[k] + dt * u[k]
    i.e.  A = I3,  B = dt * I3
where e = [ex, ey, ez] is the NED position error and u = [vx, vy, vz] is the velocity command.

Usage:
    python3 compute_lqr_gains.py
    python3 compute_lqr_gains.py --dt 0.1 --Q 1 1 2 --R 0.1 0.1 0.1 --vel-limit 3.0
"""

import argparse
import os
import numpy as np
from scipy.linalg import solve_discrete_are


def compute_lqr(A, B, Q, R):
    P = solve_discrete_are(A, B, Q, R)
    K = np.linalg.inv(R + B.T @ P @ B) @ (B.T @ P @  A)
    return K, P


def main():
    parser = argparse.ArgumentParser(description="Compute discrete LQR gains and write to YAML")
    parser.add_argument("--dt", type=float, default=0.1,
                        help="Control loop timestep in seconds (default: 0.1)")
    parser.add_argument("--Q", type=float, nargs=3, default=[1.0, 1.0, 2.0],
                        metavar=("Qx", "Qy", "Qz"),
                        help="Position error cost weights for [x, y, z] (default: 1 1 2)")
    parser.add_argument("--R", type=float, nargs=3, default=[0.1, 0.1, 0.1],
                        metavar=("Rx", "Ry", "Rz"),
                        help="Velocity command cost weights for [x, y, z] (default: 0.1 0.1 0.1)")
    parser.add_argument("--vel-limit", type=float, default=5.0,
                        help="Max velocity command magnitude m/s (default: 5.0)")
    parser.add_argument("--output", type=str,
                        default=os.path.join(os.path.dirname(__file__), "../config/lqr_gains.yaml"),
                        help="Output YAML file path")
    parser.add_argument("--enable", action="store_true", default=False,
                        help="Set use_lqr: true in output (default: false, must opt-in)")
    args = parser.parse_args()

    dt = args.dt
    A = np.eye(3)
    B = dt * np.eye(3)
    Q = np.diag(args.Q)
    R = np.diag(args.R)

    K, P = compute_lqr(A, B, Q, R)

    print("Solved DARE. Results:")
    print(f"  dt = {dt} s")
    print(f"  Q  = diag{tuple(args.Q)}")
    print(f"  R  = diag{tuple(args.R)}")
    print(f"  P  =\n{P}")
    print(f"  K  =\n{K}")
    print(f"  Closed-loop eigenvalues: {np.linalg.eigvals(A - B @ K)}")

    k_flat = K.flatten().tolist()
    k_str = ", ".join(f"{v:.8f}" for v in k_flat)

    yaml_content = f"""\
# Auto-generated by compute_lqr_gains.py - do not edit by hand.
# Re-run the script to update gains.
#
# Plant:  e[k+1] = e[k] + dt*u[k],  dt={dt} s
# State:  e = [ex, ey, ez]  NED position error (m)
# Input:  u = [vx, vy, vz]  NED velocity command (m/s)
# Q = diag{tuple(args.Q)},  R = diag{tuple(args.R)}
#
# K is 3x3 stored row-major: K[row*3 + col]
offboard_master:
  ros__parameters:
    use_lqr: {"true" if args.enable else "false"}
    lqr_vel_limit: {args.vel_limit}
    lqr_K: [{k_str}]
"""

    out_path = os.path.realpath(args.output)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(yaml_content)

    print(f"\nWrote gains to: {out_path}")
    print("Set use_lqr: true in the YAML (or pass --enable) to activate LQR in offboard_master.")


if __name__ == "__main__":
    main()
